### ISSUE TITLE
help setting the server on qnap

### ISSUE THREAD

**Issue by andrearicci** [pjimenezmateo/kindle-wallpaper#4]
hello, I have a qnap with an web server working. I tryed to setup and run your script with the following errors (lots of command missing!) can you help? maybe there's not python. maybe some configuration missing?

```
[/] # /share/MD0_DATA/Web/kindle/launch.sh
Traceback (most recent call last):
 File "programs/parse_weather.py", line 30, in <module>
 f = codecs.open(image_url ,'r', encoding='utf-8')
 File "/share/MD0_DATA/.qpkg/Python/lib/python2.7/codecs.py", line 881, in open
 file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'icons/29.svg'
Traceback (most recent call last):
 File "programs/parse_ical.py", line 1, in <module>
   from icalendar import Calendar
ImportError: No module named icalendar
/share/MD0_DATA/Web/kindle/launch.sh: line 8: rsvg-convert: command not found
/share/MD0_DATA/Web/kindle/launch.sh: line 11: pngcrush: command not found
rm: cannot remove `/share/MD0_DATA/Web/kindle/done.png': No such file or directory
BusyBox v1.01 (2015.11.17-17:32+0000) multi-call binary

Usage: mv [OPTION]... SOURCE DEST
or: mv [OPTION]... SOURCE... DIRECTORY

Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.

Options:
    -f      don't prompt before overwriting
    -i      interactive, prompt before overwrite

rm: cannot remove `basic.ics': No such file or directory
rm: cannot remove `after-weather.svg': No such file or directory
rm: cannot remove `almost_done.png': No such file or directory
rm: cannot remove `almost_done.svg': No such file or directory
[/] #
```

**Comment by pjimenezmateo** [comment]
I'm sorry for the huge delay. Let me know if this is still an issue and I will reopen.
